# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='about',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='about_0',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='about_1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='about_2',
            field=models.CharField(default='', max_length=500),
        ),
    ]
