# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='email',
            field=models.CharField(default='', max_length=40),
        ),
    ]
