# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-02 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='intro',
            field=models.CharField(max_length=250),
        ),
    ]
