# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-02 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180902_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='intro',
            new_name='heading',
        ),
    ]
